export type Deal = {
  n: string;
  p: string;
  h: string;
  b: string;
  pr: string;
  c: string;
  d: string;
  hr: string;
  desc: string;
  s: string;
  sc: number;
  tr: number;
  lat?: number;
  lng?: number;
};

export type Category = {
  k: string;
  l: string;
  i: string;
  cl: string;
};

export const CATS: Category[] = [
  { k: "All", l: "All Deals", i: "🗽", cl: "#f59e0b" },
  { k: "Dollar Eats", l: "Dollar Eats", i: "💵", cl: "#22c55e" },
  { k: "Cheap Eats", l: "Under $15", i: "🍜", cl: "#10b981" },
  { k: "$1 Oyster Deals", l: "$1 Oysters", i: "🦪", cl: "#0ea5e9" },
  { k: "Taco Tuesday", l: "Tacos", i: "🌮", cl: "#f97316" },
  { k: "Wing Wednesday", l: "Wings", i: "🍗", cl: "#ef4444" },
  { k: "Burger Deals", l: "Burgers", i: "🍔", cl: "#3b82f6" },
  { k: "Happy Hour Food", l: "Happy Hour", i: "🍻", cl: "#eab308" },
  { k: "Bottomless Brunch", l: "Brunch", i: "🥂", cl: "#ec4899" },
  { k: "Hot Restaurant Value", l: "Hot Spots", i: "🔥", cl: "#fb923c" },
  { k: "Luxury Loophole", l: "Luxury Hacks", i: "✨", cl: "#fbbf24" },
  { k: "Street Food & Markets", l: "Street Food", i: "🛒", cl: "#14b8a6" },
  { k: "Pizza Slice Value", l: "Pizza", i: "🍕", cl: "#f43f5e" },
  { k: "Fast Food Value", l: "Fast Food", i: "🍟", cl: "#f87171" },
  { k: "Prix Fixe Lunch", l: "Prix Fixe", i: "🍽️", cl: "#34d399" },
  { k: "Seasonal", l: "Seasonal", i: "📅", cl: "#22d3ee" },
  { k: "Workspace", l: "Workspaces", i: "💻", cl: "#38bdf8" },
  { k: "Free Events", l: "Free Events", i: "🎨", cl: "#a3e635" },
  { k: "Late Night", l: "Late Night", i: "🌙", cl: "#60a5fa" },
  { k: "Dim Sum", l: "Dim Sum", i: "🥡", cl: "#fb7185" },
];

export const DEALS: Deal[] = [
  // ─── DOLLAR EATS ───
  { n: "Dollar Slice Pizza", p: "2 Bros / 99¢ Fresh / Percy's", h: "Citywide", b: "Manhattan", pr: "$1–$1.50", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "NYC's unbeatable floor price. Plain cheese slice at dozens of no-frills counters across Manhattan.", s: "2-bros-pizza-cheap-slice", sc: 9, tr: 7 },
  { n: "Fried Dumplings (4 for $1.50)", p: "Vanessa's Dumpling House", h: "Chinatown / E. Village / Williamsburg", b: "Manhattan", pr: "$1.50", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "Pork with chive or cabbage. Pan-fried golden. Three locations. Cash-friendly.", s: "vanessas-dumpling-house-value", sc: 8, tr: 8 },
  { n: "Peanut Noodles + Dumplings", p: "Shu Jiao Fu Zhou", h: "Chinatown (295 Grand St)", b: "Manhattan", pr: "$3.50", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "Creamy peanut noodles under $4. Pork & chive dumplings 6 for ~$3. Chinatown legend. Cash only.", s: "shu-jiao-fu-zhou-chinatown-cheap-eats", sc: 10, tr: 8 },
  { n: "10 Steamed Dumplings", p: "Lam Zhou Handpull Noodle", h: "Chinatown (Bowery)", b: "Manhattan", pr: "$3", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "10 steamed pork dumplings for $3. Hand-pulled noodle soups also dirt cheap. Cash only.", s: "lam-zhou-dumplings", sc: 9, tr: 7 },
  { n: "BBQ Pork Bun", p: "Mei Lai Wah Bakery", h: "Chinatown (64 Bayard St)", b: "Manhattan", pr: "$1.50", c: "Dollar Eats", d: "Every Day", hr: "7am–7pm", desc: "Legendary bakery. Fluffy BBQ pork buns under $2. Always a line, always worth it.", s: "mei-lai-wah-pork-buns", sc: 8, tr: 9 },
  { n: "Scallion Pancake + Soybean Milk", p: "Zhu Ji Dumpling", h: "Flushing", b: "Queens", pr: "$3", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "Breakfast in Flushing for $3: crispy scallion pancake + fresh soybean milk.", s: "zhu-ji-flushing", sc: 9, tr: 7 },
  { n: "Steamed Buns", p: "Golden Steamer", h: "Chinatown (210 Grand St)", b: "Manhattan", pr: "~$2", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "Chinatown bakery with dirt-cheap steamed buns and snacks. Perfect under-$5 fuel.", s: "golden-steamer-chinatown-cheap-snacks", sc: 9, tr: 7 },
  { n: "Signature Rice Roll", p: "Yi Ji Shi Mo", h: "Chinatown", b: "Manhattan", pr: "~$8", c: "Dollar Eats", d: "Every Day", hr: "Breakfast/Lunch", desc: "Low-priced rice roll breakfast/lunch staple. One of the best under-$10 meals in Chinatown.", s: "yi-ji-shi-mo-rice-roll", sc: 9, tr: 7 },
  { n: "BEC (Bacon Egg & Cheese)", p: "Any bodega / deli", h: "Citywide", b: "Citywide", pr: "$4–$6", c: "Dollar Eats", d: "Every Day", hr: "Morning", desc: "The NYC breakfast staple on a roll. SPK (salt pepper ketchup). Every corner has one.", s: "bec-bodega", sc: 8, tr: 9 },
  { n: "Empanadas (street cart)", p: "Various bodegas / carts", h: "Citywide", b: "Citywide", pr: "$2–$3", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "Flaky stuffed pastries from carts, bodegas, and Hispanic groceries. Meat, cheese, or veggie.", s: "empanadas-street", sc: 8, tr: 7 },
  { n: "Pan-Fried Soup Dumplings", p: "Liu Liu Sheng Jian", h: "Flushing (New World Mall)", b: "Queens", pr: "$5–$6", c: "Dollar Eats", d: "Every Day", hr: "9am–9:30pm", desc: "Crispy-bottom sheng jian bao with hot broth inside. Watch the giant pans bubble.", s: "liu-liu-sheng-jian", sc: 9, tr: 7 },
  { n: "Roast Pork Over Rice", p: "Wah Fung No. 1 Fast Food", h: "Chinatown (79 Chrystie St)", b: "Manhattan", pr: "~$5", c: "Dollar Eats", d: "Every Day", hr: "Lunch", desc: "Extremely low-cost roast meat rice boxes. Long line, massive portions, incredible value.", s: "wah-fung-no-1-chinatown-value", sc: 9, tr: 9 },

  // ─── CHEAP EATS ───
  { n: "Recession Special (2 Franks + Drink)", p: "Gray's Papaya", h: "Upper West Side (2090 Broadway)", b: "Manhattan", pr: "$6.95", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Two franks + medium tropical drink for $6.95 including tax. A NYC institution since 1973.", s: "grays-papaya-uws-cheap-eats", sc: 8, tr: 9 },
  { n: "Spicy Cumin Lamb Noodles", p: "Xi'an Famous Foods", h: "Multiple locations", b: "Citywide", pr: "$10–$14", c: "Cheap Eats", d: "Every Day", hr: "11am–8:30pm", desc: "Hand-pulled noodles in spicy cumin lamb sauce. Started in a Flushing food court, now an empire.", s: "xian-famous-foods-nyc-value", sc: 8, tr: 10 },
  { n: "Falafel Sandwich", p: "Mamoun's Falafel", h: "Greenwich Village (119 MacDougal)", b: "Manhattan", pr: "$7–$9", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "50+ years of authentic falafel, shawarma, and kebabs. The OG of Greenwich Village cheap eats.", s: "mamouns-falafel-greenwich-village", sc: 8, tr: 9 },
  { n: "Chicken/Gyro Platter", p: "The Halal Guys", h: "Midtown (53rd & 6th)", b: "Manhattan", pr: "$9–$11", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "The original halal cart. Massive platters of chicken or gyro over rice. Lines around the block.", s: "halal-guys-midtown-value", sc: 7, tr: 10 },
  { n: "Adobada Tacos (2–3 = a meal)", p: "Los Tacos No. 1", h: "Chelsea Market / Times Square", b: "Manhattan", pr: "$4–$5/taco", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Best tacos in NYC. Homemade tortillas, real marinated pork. 2–3 tacos is a full meal under $15.", s: "los-tacos-no-1-value", sc: 8, tr: 10 },
  { n: "Birria Tacos + Consommé", p: "Birria Landia", h: "Jackson Heights / Multiple", b: "Queens", pr: "$10–$14", c: "Cheap Eats", d: "Every Day", hr: "Varies", desc: "Cult food truck/cart. Slow-cooked meat tacos with consommé for dipping. Went viral for a reason.", s: "birria-landia-nyc-value", sc: 8, tr: 9 },
  { n: "Wontons w/ Hot Sauce (#6)", p: "White Bear", h: "Flushing", b: "Queens", pr: "$6–$8", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Tiny takeout window. Order #6: 12 pork wontons in chili oil. Impossibly soft.", s: "white-bear-flushing", sc: 9, tr: 7 },
  { n: "Al Pastor Burrito", p: "Nene's Deli Taqueria", h: "Bushwick / Park Slope", b: "Brooklyn", pr: "~$14", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Strong under-$15 burrito and quesabirria value. Multiple Brooklyn locations.", s: "nenes-deli-taqueria-burrito-value", sc: 8, tr: 8 },
  { n: "Banh Mi", p: "Banh Mi Saigon", h: "Chinatown (198 Grand St)", b: "Manhattan", pr: "~$10", c: "Cheap Eats", d: "Every Day", hr: "Lunch", desc: "Classic Chinatown banh mi. Crispy baguette, pickled daikon, cilantro, your choice of protein.", s: "banh-mi-saigon-chinatown-value", sc: 8, tr: 8 },
  { n: "Pierogis (24-hour)", p: "Veselka", h: "East Village (144 2nd Ave)", b: "Manhattan", pr: "$9 for 4", c: "Cheap Eats", d: "Every Day", hr: "24 hours", desc: "Open since 1954. Boiled or fried pierogis with sautéed onions and sour cream. Open 24 hours.", s: "veselka-east-village-value", sc: 6, tr: 9 },
  { n: "Empanadas (dozen varieties)", p: "Empanada Mama", h: "Hell's Kitchen / Multiple", b: "Manhattan", pr: "$3–$5 each", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Cuban, shredded chicken, pernil, chorizo — dozens of fillings. Portable, filling, cheap.", s: "empanada-mama", sc: 8, tr: 7 },
  { n: "Ethiopian Lunch Special", p: "Bunna Cafe", h: "Bushwick", b: "Brooklyn", pr: "$13–$15", c: "Cheap Eats", d: "Every Day", hr: "Lunch", desc: "All plant-based Ethiopian. Choose 4 items: chickpeas, lentils, beets, string beans. Communal injera.", s: "bunna-cafe-bushwick", sc: 8, tr: 7 },
  { n: "Hand-Pulled Noodle Soups", p: "Tasty Hand-Pulled Noodles", h: "Chinatown", b: "Manhattan", pr: "~$12", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Large noodle portions at accessible prices. Watch them stretch the dough in front of you.", s: "tasty-hand-pulled-noodles-value", sc: 8, tr: 7 },
  { n: "Caribbean Seafood", p: "Calle 191 Pescaderia", h: "Washington Heights", b: "Manhattan", pr: "$10–$14", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Hidden gem seafood market + outdoor café. Crab Meat Creole, Shrimp Mofongo. All under $15.", s: "calle-191-heights", sc: 8, tr: 6 },
  { n: "Food Court Feast (30+ vendors)", p: "New World Mall Food Court", h: "Flushing", b: "Queens", pr: "$6–$14", c: "Cheap Eats", d: "Every Day", hr: "9am–9:30pm", desc: "30+ stalls: dry pot, noodles, soup dumplings, roast duck. Bring cash.", s: "new-world-mall-flushing", sc: 9, tr: 8 },
  { n: "Potstickers + Braised Pork Rice", p: "A-Pou's Taste", h: "East Williamsburg", b: "Brooklyn", pr: "~$12.50", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Two-item value combo around $12.50 total. Taiwanese comfort food in East Williamsburg.", s: "apous-taste-east-williamsburg-value", sc: 9, tr: 7 },
  { n: "Beef Jhol Momo + Sel Roti", p: "Nepali Bhanchha Ghar", h: "Jackson Heights", b: "Queens", pr: "~$14", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Strong value combo under $15. Nepali momos with rich gravy plus fried bread.", s: "nepali-bhanchha-ghar-jackson-heights-value", sc: 9, tr: 8 },
  { n: "$14 Lunch Special (dim sum)", p: "Dim Sum Palace", h: "Midtown / Times Square", b: "Manhattan", pr: "$14", c: "Cheap Eats", d: "Every Day", hr: "Lunch", desc: "Lunch special reportedly includes rice and soup. Solid Midtown cheap lunch option.", s: "dim-sum-palace-midtown-lunch-special", sc: 8, tr: 7 },
  { n: "Pasta Bowls Under $15", p: "Maestro Pasta", h: "FiDi", b: "Manhattan", pr: "<$15", c: "Cheap Eats", d: "Every Day", hr: "Lunch", desc: "Fast casual pasta bowls and half-bowls (from ~$6). Great FiDi office lunch.", s: "maestro-pasta-fidi-cheap-lunch", sc: 9, tr: 6 },
  { n: "Vegetarian Plate / Samosas", p: "Punjabi Deli", h: "Lower East Side (114 E 1st St)", b: "Manhattan", pr: "~$8", c: "Cheap Eats", d: "Every Day", hr: "All day / Late", desc: "Classic taxi-driver vegetarian value spot. Open late. Samosas, dal, veggie plates.", s: "punjabi-deli-les-cheap-eats", sc: 9, tr: 8 },
  { n: "Diablada Broster", p: "Bolivian Llama Party", h: "Sunnyside", b: "Queens", pr: "~$13.50", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Bolivian fried chicken with spicy sauce. Outstanding Queens under-$15 value.", s: "bolivian-llama-party-sunnyside-value", sc: 8, tr: 7 },
  { n: "Halal Platter", p: "Kwik Meal", h: "Midtown (100 W 45th St)", b: "Manhattan", pr: "$10–$15", c: "Cheap Eats", d: "Every Day", hr: "Lunch/Dinner", desc: "Legendary Midtown halal restaurant. Massive portions, great lamb.", s: "kwik-meal-midtown-halal-value", sc: 8, tr: 7 },
  { n: "Smash Burger", p: "7th Street Burger", h: "Multiple locations", b: "Citywide", pr: "~$7+", c: "Cheap Eats", d: "Every Day", hr: "All day / Late", desc: "Fast casual smash burgers with many locations. Strong late-night value.", s: "7th-street-burger-value", sc: 8, tr: 9 },
  { n: "Kati Rolls (Late Night)", p: "Kolachi", h: "East Village", b: "Manhattan", pr: "~$15–$16", c: "Cheap Eats", d: "Every Day", hr: "Late Night", desc: "Two kati rolls for ~$15–$16. Indian/Pakistani late-night value in the East Village.", s: "kolachi-east-village-late-night", sc: 8, tr: 7 },
  { n: "Fried Chicken / Wrap", p: "Bobwhite Counter", h: "East Village", b: "Manhattan", pr: "<$15", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Reliable under-$15 fried chicken and buffalo chicken wrap. Great near-NYU spot.", s: "bobwhite-counter-east-village-value", sc: 7, tr: 8 },
  { n: "Rotisserie Chicken Meal", p: "Caravan Chicken", h: "Astoria", b: "Queens", pr: "<$20", c: "Cheap Eats", d: "Every Day", hr: "All day", desc: "Peruvian-style rotisserie chicken. Strong family/portion value under $20.", s: "caravan-chicken-astoria-value", sc: 8, tr: 7 },

  // ─── OYSTER DEALS ───
  { n: "$2 Oysters + HH Snacks", p: "Mermaid Oyster Bar", h: "Times Square (127 W 43rd St)", b: "Manhattan", pr: "$2/ea", c: "$1 Oyster Deals", d: "Daily", hr: "4pm–5:30pm (Mon all night)", desc: "Chef's choice oysters $2. Monday HH runs ALL NIGHT. Great pre-theater stop.", s: "mermaid-oyster-bar-times-square-happy-hour", sc: 9, tr: 8 },
  { n: "$2–$3.50 Oysters", p: "Crave Fishbar", h: "UWS / Midtown East", b: "Manhattan", pr: "$2–$3.50/ea", c: "$1 Oyster Deals", d: "Daily/varies", hr: "Happy Hour", desc: "Assorted oysters $2–$3.50 range plus discounted food/drinks. Multiple locations.", s: "crave-fishbar-oyster-happy-hour", sc: 8, tr: 8 },
  { n: "$25 Dozen Oysters", p: "Grand Army", h: "Boerum Hill (336 State St)", b: "Brooklyn", pr: "$25/dozen", c: "$1 Oyster Deals", d: "Wed–Sun", hr: "4–6pm (Sat 2–4pm)", desc: "Dozen oysters for $25 plus discounted wine/beer. Clean Brooklyn deal.", s: "grand-army-boerum-hill-oyster-happy-hour", sc: 8, tr: 7 },
  { n: "$9 Half-Dozen + $6 Hot Dog", p: "OTB", h: "Williamsburg (141 Broadway)", b: "Brooklyn", pr: "$9/half-doz", c: "$1 Oyster Deals", d: "Weekdays", hr: "4–6pm", desc: "Oysters and bar food HH. Pool tables, Lone Stars, strong cool-but-cheap positioning.", s: "otb-williamsburg-oyster-happy-hour", sc: 9, tr: 7 },
  { n: "$1.50 Oysters", p: "Due West", h: "West Village (189 W 10th St)", b: "Manhattan", pr: "$1.50/ea", c: "$1 Oyster Deals", d: "Varies", hr: "Happy Hour", desc: "West Village oyster HH. Cozy neighborhood spot.", s: "due-west-west-village-oyster-happy-hour", sc: 8, tr: 7 },
  { n: "$1 Oysters", p: "John Doe", h: "NoMad", b: "Manhattan", pr: "$1/ea", c: "$1 Oyster Deals", d: "Daily/varies", hr: "Happy Hour", desc: "$1 oyster happy hour in NoMad. Call to verify current days/times.", s: "john-doe-nomad-oyster-happy-hour", sc: 8, tr: 5 },
  { n: "$15 Dozen + $7 Sliders", p: "The Summit Bar", h: "East Village (133 Ave C)", b: "Manhattan", pr: "$15/dozen", c: "$1 Oyster Deals", d: "Daily", hr: "5–8pm", desc: "Daily HH with raw East Coast oysters and pulled pork sliders.", s: "the-summit-bar-east-village-happy-hour", sc: 9, tr: 6 },
  { n: "Waterfront Oyster HH", p: "Grand Banks", h: "Tribeca (Pier 25)", b: "Manhattan", pr: "Varies", c: "$1 Oyster Deals", d: "Seasonal", hr: "Varies", desc: "Waterfront oyster/bar specials vary seasonally. Iconic boat bar on the Hudson.", s: "grand-banks-nyc-oyster-happy-hour", sc: 7, tr: 8 },
  { n: "Boat Oyster HH", p: "Pilot", h: "Brooklyn Heights (Pier 6)", b: "Brooklyn", pr: "Varies", c: "$1 Oyster Deals", d: "Seasonal", hr: "Varies", desc: "Boat restaurant with seasonal seafood specials. Great summer deal candidate.", s: "pilot-brooklyn-oyster-happy-hour", sc: 7, tr: 8 },
  { n: "$1 Oysters All Day", p: "Upstate", h: "East Village", b: "Manhattan", pr: "$1/ea", c: "$1 Oyster Deals", d: "Every Day", hr: "Open–7pm", desc: "$1 oysters daily, max 12/guest. Cocktails $14, wine $10. Romantic date spot.", s: "upstate-east-village", sc: 9, tr: 7 },
  { n: "$1.50 Oysters + $1.50 Clams", p: "Dock's Oyster Bar", h: "Midtown (40th & Broadway)", b: "Manhattan", pr: "$1.50/ea", c: "$1 Oyster Deals", d: "Every Day", hr: "3–7pm (bar)", desc: "$1.50 oyster du jour + clams, $3 beef slider, $6 drafts, $8 fish tacos.", s: "docks-oyster-bar", sc: 9, tr: 7 },
  { n: "$1 Oysters (Waterfront)", p: "Brooklyn Crab", h: "Red Hook", b: "Brooklyn", pr: "$1/ea", c: "$1 Oyster Deals", d: "Mon–Fri", hr: "Before 6pm", desc: "$1 oysters at a 3-floor waterfront bar with cornhole and beachside vibes.", s: "brooklyn-crab-red-hook", sc: 9, tr: 7 },

  // ─── TACO DEALS ───
  { n: "$1 Rooftop Tacos (Saturday)", p: "The Ready Rooftop", h: "East Village (112 E 11th St)", b: "Manhattan", pr: "$1/taco", c: "Taco Tuesday", d: "Saturday", hr: "12–3pm", desc: "$1 tacos on a rooftop in the East Village. High viral potential. Saturday only.", s: "the-ready-rooftop-dollar-tacos", sc: 10, tr: 9 },
  { n: "$5 Tacos + $10 Cocktails", p: "Frijoleros", h: "Greenpoint", b: "Brooklyn", pr: "$5/taco", c: "Taco Tuesday", d: "Weekdays", hr: "Until 6pm", desc: "Weekday HH with tacos and classic cocktails at one of Brooklyn's hottest new Mexican spots.", s: "frijoleros-greenpoint-happy-hour", sc: 8, tr: 8 },
  { n: "Endless Tacos + Free Marg", p: "Mad Dog & Beans", h: "Midtown (5 E. 38th St)", b: "Manhattan", pr: "$19.95 AYCE", c: "Taco Tuesday", d: "Tuesday", hr: "6–9pm", desc: "Bottomless tacos 6–9pm with a FREE frozen margarita. All you can eat for $19.95.", s: "mad-dog-beans-taco-tuesday", sc: 7, tr: 6 },
  { n: "$2 Tacos", p: "Eastpoint", h: "East Village (25 Ave B)", b: "Manhattan", pr: "$2/taco", c: "Taco Tuesday", d: "Tuesday", hr: "All day", desc: "$2 tacos every Tuesday. No gimmicks, just cheap tacos in the East Village.", s: "eastpoint-taco-tuesday", sc: 8, tr: 7 },
  { n: "2 Tacos for $5–$6", p: "East End Bar & Grill", h: "UES (1664 1st Ave)", b: "Manhattan", pr: "$5 for 2", c: "Taco Tuesday", d: "Tuesday", hr: "All day", desc: "Beef or chicken 2/$5. Fish, shrimp, carne asada, al pastor, pulled pork 2/$6.", s: "east-end-bar-tacos", sc: 8, tr: 6 },
  { n: "$3 Tacos + $5 Margaritas", p: "All-Stars Bar & Grill", h: "Hell's Kitchen (327 W. 57th)", b: "Manhattan", pr: "$3/taco", c: "Taco Tuesday", d: "Tuesday", hr: "All day", desc: "$3 chicken or beef tacos, $5 margaritas every Tuesday.", s: "all-stars-taco-tuesday", sc: 7, tr: 6 },
  { n: "$5 Tacos + $7 Margs + Live Music", p: "Mason Jar NYC", h: "Midtown", b: "Manhattan", pr: "$5/taco", c: "Taco Tuesday", d: "Tuesday", hr: "All day (dine-in)", desc: "$5 tacos (beef, pork, fish, chicken), $7 margs, live music at 6pm.", s: "mason-jar-taco-tuesday", sc: 7, tr: 6 },
  { n: "$20 AYCE Tacos (Tue + Wed)", p: "Barrio Taqueria", h: "Queens", b: "Queens", pr: "$20 AYCE", c: "Taco Tuesday", d: "Tue & Wed", hr: "All day (1hr limit)", desc: "$20 unlimited tacos: al pastor, tinga, mushroom, chicken, chorizo. 1-hour limit.", s: "barrio-taqueria-ayce", sc: 8, tr: 8 },
  { n: "$2 Birria Tacos", p: "Colima Taqueria", h: "Bronx (608 E 187th St)", b: "Bronx", pr: "$2/taco", c: "Taco Tuesday", d: "Tuesday", hr: "12–6pm", desc: "$2 birria tacos every Tuesday noon to 6pm. Bronx gem.", s: "colima-taqueria-birria", sc: 9, tr: 8 },

  // ─── WING WEDNESDAY ───
  { n: "50¢ Wings (7pm–midnight)", p: "Various NYC bars", h: "Multiple", b: "Manhattan", pr: "$0.50/wing", c: "Wing Wednesday", d: "Wednesday", hr: "7pm–midnight", desc: "50-cent wings from 7pm to midnight at multiple Manhattan bars.", s: "fifty-cent-wings", sc: 8, tr: 7 },
  { n: "Half-Price Wings", p: "UES bars", h: "Upper East Side", b: "Manhattan", pr: "50% off", c: "Wing Wednesday", d: "Wednesday", hr: "Varies", desc: "Half-price wings across UES. Some top finishers in citywide Lord of the Wings challenge.", s: "ues-half-price-wings", sc: 8, tr: 7 },
  { n: "10¢ Wings", p: "Select bars", h: "Various", b: "Manhattan", pr: "$0.10/wing", c: "Wing Wednesday", d: "Wednesday", hr: "Varies", desc: "Yes, dime wings still exist at a few NYC bars.", s: "dime-wings", sc: 9, tr: 6 },
  { n: "20 Wings for $10 (Carryout)", p: "Pizza Hut", h: "Multiple", b: "Citywide", pr: "$10/20", c: "Wing Wednesday", d: "Wednesday", hr: "All day", desc: "20 lil' wings for $10. Carryout only, limit 6 orders.", s: "pizza-hut-wings", sc: 7, tr: 6 },

  // ─── BURGER DEALS ───
  { n: "2-for-1 Cheeseburgers", p: "Mason Jar NYC", h: "Midtown", b: "Manhattan", pr: "BOGO", c: "Burger Deals", d: "Wednesday", hr: "All day", desc: "BOGO Double Bacon Cheeseburgers all day Wednesday. Beverage purchase required.", s: "mason-jar-bogo-burger", sc: 8, tr: 6 },
  { n: "$20 Burger + Beer", p: "Golden HOF", h: "Midtown (16 W 48th St)", b: "Manhattan", pr: "$20 combo", c: "Burger Deals", d: "Daily", hr: "3–6pm", desc: "Burger + beer combo plus $10 cocktails and $6 beers during HH. Great Midtown office deal.", s: "golden-hof-midtown-burger-beer-deal", sc: 8, tr: 8 },
  { n: "$3.99 Whopper Wednesday", p: "Burger King", h: "Multiple", b: "Citywide", pr: "$3.99", c: "Burger Deals", d: "Wednesday", hr: "All day (app)", desc: "$3.99 Whopper (regular or Impossible) via the BK app every Wednesday.", s: "bk-whopper-wednesday", sc: 7, tr: 7 },
  { n: "Half-Price Cheeseburgers", p: "Sonic", h: "Various", b: "Citywide", pr: "50% off", c: "Burger Deals", d: "Tuesday", hr: "After 5pm", desc: "Half-price cheeseburgers every Tuesday evening at Sonic.", s: "sonic-half-price", sc: 7, tr: 6 },

  // ─── HAPPY HOUR ───
  { n: "$15 Pasta + $10 Drinks", p: "Popina", h: "Columbia Waterfront (127 Columbia St)", b: "Brooklyn", pr: "$15 pasta", c: "Happy Hour Food", d: "Mon–Thu", hr: "Happy Hour", desc: "Happy hour pasta and drinks at a respected Brooklyn restaurant. Also: no-corkage Wednesday.", s: "popina-brooklyn-happy-hour-pasta", sc: 9, tr: 9 },
  { n: "Martini Hour + Snacks ($8–$20)", p: "Koloman", h: "NoMad (16 W 29th St)", b: "Manhattan", pr: "$12 cocktails", c: "Happy Hour Food", d: "Tue–Sun", hr: "4–7pm", desc: "Upscale NoMad Austrian/French restaurant with martini hour and lower-priced bar snacks.", s: "koloman-nomad-martini-hour", sc: 8, tr: 9 },
  { n: "$7 Bites + $5 Prosecco", p: "PHD Terrace", h: "Midtown (210 W 55th St)", b: "Manhattan", pr: "$5–$7", c: "Happy Hour Food", d: "Tue–Fri", hr: "5–7pm", desc: "Published happy hour with $7 bites and $5 prosecco on a Midtown rooftop. Strong SEO for rooftop value.", s: "phd-terrace-rooftop-happy-hour", sc: 8, tr: 8 },
  { n: "Half-Off Signature Cocktails", p: "Red Rooster", h: "Harlem (310 Lenox Ave)", b: "Manhattan", pr: "50% off", c: "Happy Hour Food", d: "Mon–Thu", hr: "5–7pm", desc: "Harlem hotspot with half-off cocktails on weekdays. Marcus Samuelsson's flagship.", s: "red-rooster-harlem-happy-hour", sc: 7, tr: 8 },
  { n: "Cocktails + Raw Bar", p: "The Dynamo Room", h: "Penn Station (2 Penn Plaza)", b: "Manhattan", pr: "$13.95 cocktails", c: "Happy Hour Food", d: "Varies", hr: "Happy Hour", desc: "Steakhouse-adjacent bar near MSG with discounted cocktails and raw bar. Great pre-event.", s: "dynamo-room-msg-happy-hour", sc: 7, tr: 8 },
  { n: "$15.95 Fajita Night + Free Marg", p: "Mad Dog & Beans", h: "Midtown (5 E. 38th St)", b: "Manhattan", pr: "$15.95", c: "Happy Hour Food", d: "Wednesday", hr: "6–9pm", desc: "Your choice of fajita + one FREE frozen margarita for $15.95.", s: "mad-dog-fajita-night", sc: 7, tr: 6 },
  { n: "$5 Margaritas ALL DAY", p: "Mexican bars", h: "Multiple", b: "Manhattan", pr: "$5", c: "Happy Hour Food", d: "Wednesday", hr: "All day", desc: "$5 margaritas all day and all night at the bar. Acoustic live music 7–10pm.", s: "five-dollar-margs", sc: 8, tr: 7 },
  { n: "Standard NYC HH ($4–$6)", p: "Dozens of bars", h: "Citywide", b: "Manhattan", pr: "$4–$6", c: "Happy Hour Food", d: "Mon–Fri", hr: "4–7pm", desc: "$4 domestic bottles, $5 craft drafts, $6 wells/wine. The NYC baseline.", s: "standard-nyc-happy-hour", sc: 6, tr: 8 },

  // ─── BOTTOMLESS BRUNCH ───
  { n: "$14 Bottomless Rosé Mimosas", p: "Various (per SecretNYC)", h: "Multiple", b: "Manhattan", pr: "$14", c: "Bottomless Brunch", d: "Sat–Sun", hr: "Brunch", desc: "$14 bottomless rosé mimosas, classic mimosas, or sangria with food. Cheapest bottomless in NYC.", s: "fourteen-dollar-bottomless", sc: 9, tr: 8 },
  { n: "$19.95 Bottomless + Live Music", p: "Beatstro", h: "Multiple", b: "Manhattan", pr: "$19.95", c: "Bottomless Brunch", d: "Sat–Sun", hr: "90 min", desc: "$19.95 for 90 min unlimited sangria/mimosas with live music. Chicken & waffles, rum cake french toast.", s: "beatstro-bottomless", sc: 8, tr: 7 },
  { n: "$25 Bottomless (90 min)", p: "Sweet Afton / Bonnie's", h: "Astoria / Multiple", b: "Queens", pr: "$25", c: "Bottomless Brunch", d: "Sat–Sun", hr: "90 min", desc: "$25 for 90 min unlimited mimosas, bloody marys, sangria, or beer with entrée.", s: "sweet-afton-bottomless", sc: 8, tr: 7 },
  { n: "$32 Prix Fixe + Bottomless", p: "Ainslie", h: "Bowery", b: "Manhattan", pr: "$32", c: "Bottomless Brunch", d: "Sat–Sun", hr: "90 min", desc: "$32 for 1.5 hours unlimited brunch cocktails with any entrée. Three-floor venue.", s: "ainslie-bottomless", sc: 8, tr: 7 },
  { n: "$39.50 Steak Frites + Bottomless", p: "Medium Rare", h: "Multiple", b: "Manhattan", pr: "$39.50", c: "Bottomless Brunch", d: "Sat–Sun", hr: "Brunch", desc: "Steak frites ($34.95 at dinner) — at brunch add bottomless for $5 more.", s: "medium-rare-bottomless", sc: 7, tr: 7 },
  { n: "$40 Wood-Fired Pizza + Bottomless", p: "Carroll Place", h: "Greenwich Village", b: "Manhattan", pr: "$40", c: "Bottomless Brunch", d: "Sat–Sun", hr: "90 min", desc: "$40 for 90 min Mimosas/Bloody Marys/Sangria with entrée. Wood-fired oven.", s: "carroll-place-bottomless", sc: 7, tr: 7 },
  { n: "$40 Endless Tacos + Margs", p: "Taco Vision", h: "Midtown East", b: "Manhattan", pr: "$40", c: "Bottomless Brunch", d: "Sat–Sun", hr: "Brunch", desc: "Endless tacos + bottomless margaritas/mimosas. Bi-level with Margarita Garden patio.", s: "taco-vision-bottomless", sc: 7, tr: 7 },

  // ─── FAST FOOD ───
  { n: "$5 Cravings Box", p: "Taco Bell", h: "Multiple", b: "Citywide", pr: "$5", c: "Fast Food Value", d: "Every Day", hr: "All day", desc: "Beefy 5-Layer Burrito + Taco + Twists + drink. App $7 box = Crunchwrap + Burrito + Baja Blast.", s: "taco-bell-box", sc: 7, tr: 8 },
  { n: "Free Chicken Shack Sunday", p: "Shake Shack", h: "Multiple", b: "Citywide", pr: "FREE", c: "Fast Food Value", d: "Sunday", hr: "All day", desc: "Free chicken sandwich Sundays w/$10 min. Code: CHICKENSUNDAY. Through June 2026.", s: "shake-shack-free-sunday", sc: 8, tr: 8 },
  { n: "$9.99 Bottomless Apps", p: "Buffalo Wild Wings", h: "Multiple", b: "Citywide", pr: "$9.99", c: "Fast Food Value", d: "Every Day", hr: "All day", desc: "$9.99 Mix & Match Bottomless Appetizers. Through June 2026.", s: "bww-bottomless-apps", sc: 7, tr: 7 },
  { n: "Under $3 Menu", p: "McDonald's", h: "Multiple", b: "Citywide", pr: "$3–$6", c: "Fast Food Value", d: "Every Day", hr: "All day", desc: "McValue Under $3 menu + $4 breakfast. Manhattan = ~$6. Free medium fries Fridays via app.", s: "mcdonalds-mcvalue", sc: 6, tr: 8 },

  // ─── PRIX FIXE ───
  { n: "$29 Three-Course Steakhouse", p: "Gallagher's Steakhouse", h: "Midtown (228 W 52nd St)", b: "Manhattan", pr: "$29", c: "Prix Fixe Lunch", d: "Mon–Fri", hr: "Until 4pm", desc: "Three-course prix fixe at a classic steakhouse for $29. One of the best lunch deals in the city.", s: "gallaghers-prix-fixe", sc: 9, tr: 7 },
  { n: "$30 French Bistro Lunch", p: "Café D'Alsace", h: "Yorkville (2nd & 88th)", b: "Manhattan", pr: "$30", c: "Prix Fixe Lunch", d: "Mon–Fri", hr: "11:30am–3:30pm", desc: "Three-course French lunch that changes daily. Friday = Moules Frites au Curry.", s: "cafe-dalsace-prix-fixe", sc: 8, tr: 6 },
  { n: "$36.50 Three-Course Greek", p: "Avra (Rockefeller Center)", h: "Midtown", b: "Manhattan", pr: "$36.50", c: "Prix Fixe Lunch", d: "Every Day", hr: "11:30am–4pm", desc: "Three-course Greek prix fixe. Amazing outdoor seating at Rock Center.", s: "avra-prix-fixe", sc: 8, tr: 7 },
  { n: "$45 Power Lunch (Steak)", p: "STK", h: "Multiple", b: "Manhattan", pr: "$45", c: "Prix Fixe Lunch", d: "Mon–Fri", hr: "Lunch", desc: "2.5-course Power Lunch with filet mignon, tuna tartare tacos, chicken, or pasta.", s: "stk-power-lunch", sc: 7, tr: 7 },

  // ─── HOT RESTAURANT VALUE ───
  { n: "Indian Fried Chicken Sando", p: "Rowdy Rooster", h: "East Village", b: "Manhattan", pr: "<$15", c: "Hot Restaurant Value", d: "Every Day", hr: "All day", desc: "Hot casual restaurant from the Dhamaka team with accessible items. Indian-spiced fried chicken.", s: "rowdy-rooster-east-village-value", sc: 7, tr: 9 },
  { n: "High-Quality Tacos", p: "Taqueria Ramirez", h: "Greenpoint", b: "Brooklyn", pr: "~$5/taco", c: "Hot Restaurant Value", d: "Every Day", hr: "All day", desc: "One of NYC's hottest taco spots with accessible à la carte pricing relative to demand.", s: "taqueria-ramirez-greenpoint-value", sc: 7, tr: 10 },
  { n: "Veggie Burger / Gelato", p: "Superiority Burger", h: "East Village", b: "Manhattan", pr: "<$15", c: "Hot Restaurant Value", d: "Every Day", hr: "All day", desc: "Hot vegetarian spot with some of the most affordable items on any trendy menu. Cult following.", s: "superiority-burger-east-village-value", sc: 6, tr: 10 },
  { n: "Udon Bowls", p: "Raku", h: "East Village / SoHo", b: "Manhattan", pr: "<$20", c: "Hot Restaurant Value", d: "Every Day", hr: "All day", desc: "High-quality udon where selective ordering stays under $20. Not a deal — just great value.", s: "raku-nyc-udon-value", sc: 6, tr: 9 },
  { n: "Smash Burger", p: "Hamburger America", h: "SoHo", b: "Manhattan", pr: "<$15", c: "Hot Restaurant Value", d: "Every Day", hr: "All day", desc: "Hot new burger spot with accessible per-item pricing. Classic smash style.", s: "hamburger-america-soho-value", sc: 7, tr: 10 },
  { n: "Retro Lunch Counter", p: "S&P Lunch", h: "Flatiron (174 5th Ave)", b: "Manhattan", pr: "<$15", c: "Hot Restaurant Value", d: "Every Day", hr: "Breakfast/Lunch", desc: "Trendy retro lunch counter with classic sandwiches at reasonable prices.", s: "sp-lunch-flatiron-value", sc: 6, tr: 9 },

  // ─── LUXURY LOOPHOLE ───
  { n: "Aperitivo / Cocktail Value", p: "Dante", h: "Greenwich Village", b: "Manhattan", pr: "Varies", c: "Luxury Loophole", d: "Varies", hr: "Aperitivo hours", desc: "World-famous cocktail bar. Not always a deal, but aperitivo-style drinks at a bucket-list bar.", s: "dante-nyc-aperitivo-happy-hour", sc: 6, tr: 10 },
  { n: "French Brasserie Late-Night", p: "L'Express", h: "Gramercy (249 Park Ave S)", b: "Manhattan", pr: "<$25", c: "Luxury Loophole", d: "Every Day", hr: "All day / Late", desc: "Classic French brasserie that's surprisingly affordable for what you get. Open late.", s: "lexpress-gramercy-value", sc: 6, tr: 7 },

  // ─── STREET FOOD ───
  { n: "$6-Capped Food Items (Sat market)", p: "Queens Night Market", h: "Flushing Meadows-Corona Park", b: "Queens", pr: "$6/item", c: "Street Food & Markets", d: "Saturday (seasonal)", hr: "4pm–midnight", desc: "Seasonal Saturday market with 80+ vendors and capped affordable pricing. Must-visit event.", s: "queens-night-market-six-dollar-food", sc: 10, tr: 9 },
  { n: "Chicken Over Rice", p: "Adel's Famous Halal Food", h: "Midtown (49th & 6th Ave)", b: "Manhattan", pr: "$8–$12", c: "Street Food & Markets", d: "Every Day", hr: "Evening / Late Night", desc: "Cult halal cart with massive portions. Long lines = good sign.", s: "adels-famous-halal-food-value", sc: 8, tr: 10 },
  { n: "Falafel/Shawarma Platter", p: "King of Falafel & Shawarma", h: "Astoria", b: "Queens", pr: "$8–$12", c: "Street Food & Markets", d: "Every Day", hr: "All day", desc: "Queens street food staple. Enormous portions of shawarma and falafel.", s: "king-of-falafel-astoria-value", sc: 8, tr: 8 },
  { n: "Waterfront Bar Food", p: "Frying Pan", h: "Chelsea (Pier 66)", b: "Manhattan", pr: "Varies", c: "Street Food & Markets", d: "Seasonal", hr: "Afternoon–Night", desc: "Not always a deal, but strong casual waterfront value. Burgers, clam chowder, beers on a lightship.", s: "frying-pan-chelsea-waterfront-food-deals", sc: 6, tr: 8 },
  { n: "Cheap Lunch Food Hall", p: "Urbanspace Vanderbilt", h: "Midtown East (230 Park Ave)", b: "Manhattan", pr: "$10–$15", c: "Street Food & Markets", d: "Weekdays", hr: "Lunch", desc: "Food hall with multiple fast-casual vendors. Strong Midtown office lunch rotation.", s: "urbanspace-vanderbilt-cheap-lunch", sc: 6, tr: 7 },
  { n: "Budget Food Hall Route", p: "Essex Market", h: "Lower East Side (88 Essex St)", b: "Manhattan", pr: "$8–$15", c: "Street Food & Markets", d: "Every Day", hr: "All day", desc: "Multiple affordable vendors: Puebla tacos, dumplings, pizza, Shopsin's. Good LES hub.", s: "essex-market-cheap-eats", sc: 7, tr: 7 },

  // ─── PIZZA ───
  { n: "Classic NYC Slice", p: "Joe's Pizza", h: "Multiple locations", b: "Manhattan", pr: "~$3.50/slice", c: "Pizza Slice Value", d: "Every Day", hr: "All day", desc: "Iconic slice remains a relatively cheap NYC meal. Tourist-approved, local-validated.", s: "joes-pizza-nyc-slice-value", sc: 7, tr: 10 },
  { n: "High-Quality Artisan Slice", p: "Scarr's Pizza", h: "Lower East Side", b: "Manhattan", pr: "~$4.50/slice", c: "Pizza Slice Value", d: "Every Day", hr: "All day", desc: "Hot slice shop with hand-milled flour. Worth the premium over dollar slice.", s: "scarrs-pizza-les-value", sc: 7, tr: 10 },
  { n: "Burrata Slice", p: "L'Industrie Pizzeria", h: "Williamsburg / West Village", b: "Brooklyn", pr: "~$5/slice", c: "Pizza Slice Value", d: "Every Day", hr: "All day", desc: "Cult-favorite slice shop. The burrata slice is the move. Strong value-to-quality ratio.", s: "lindustrie-pizzeria-value", sc: 7, tr: 10 },
  { n: "Pepperoni Square Slice", p: "Prince Street Pizza", h: "Nolita", b: "Manhattan", pr: "~$5/slice", c: "Pizza Slice Value", d: "Every Day", hr: "All day", desc: "Tourist-heavy but the spicy pepperoni square is worth one visit. Expect a line.", s: "prince-street-pizza-slice-value", sc: 6, tr: 9 },

  // ─── SEASONAL ───
  { n: "Restaurant Week Summer 2026", p: "600+ restaurants", h: "All 5 boroughs", b: "Citywide", pr: "$30/$45/$60", c: "Seasonal", d: "Jul–Aug 2026", hr: "Lunch & Dinner", desc: "Bi-annual city program. Prix fixe at $30/$45/$60. 600+ restaurants. Excludes Saturdays.", s: "restaurant-week-summer-2026", sc: 8, tr: 9 },
  { n: "Savor NYC (Year-Round)", p: "Various", h: "Citywide", b: "Citywide", pr: "Varies", c: "Seasonal", d: "Year-round", hr: "Varies", desc: "NYC Tourism's year-round dining discovery program between Restaurant Week seasons.", s: "savor-nyc", sc: 6, tr: 7 },

  // ─── HAPPY HOUR (additional from Founder DB) ───
  { n: "$3 Tacos + $6 Nachos HH", p: "Street Taco", h: "Murray Hill", b: "Manhattan", pr: "$3/taco", c: "Happy Hour Food", d: "Every Day", hr: "4–7pm & 10pm–Close", desc: "$3 mini tacos, $6 nachos, $9 margaritas. Double happy hour: afternoon and late-night.", s: "street-taco-murray-hill-hh", sc: 8, tr: 7, lat: 40.7431, lng: -73.9774 },
  { n: "$4 Beers + $5 Cocktails", p: "Roey's", h: "West Village", b: "Manhattan", pr: "$4–$5", c: "Happy Hour Food", d: "Every Day", hr: "4–6pm", desc: "$4 beers, $5 cocktails, $6 wine, $6 pizza slices. The West Village daily happy hour.", s: "roeys-west-village-hh", sc: 8, tr: 7, lat: 40.7380, lng: -74.0001 },
  { n: "$5 Well Drinks All Evening", p: "Tile Bar", h: "East Village", b: "Manhattan", pr: "$5", c: "Happy Hour Food", d: "Every Day", hr: "5–8pm", desc: "$5 well drinks in a classic East Village dive bar setting. No frills, just cheap drinks.", s: "tile-bar-east-village-hh", sc: 8, tr: 7, lat: 40.7285, lng: -73.9840 },
  { n: "$1 Wings + $1 Oysters HH", p: "Claw Daddy's", h: "Lower East Side", b: "Manhattan", pr: "$1/wing", c: "Happy Hour Food", d: "Every Day", hr: "12–5pm", desc: "$1 wings, $1 oysters, $7 beer, $9 Adult Capri Suns. Daily afternoon deal in LES.", s: "claw-daddys-les-hh", sc: 9, tr: 8, lat: 40.7181, lng: -73.9895 },

  // ─── WORKSPACES ───
  { n: "Ace Hotel Lobby", p: "Ace Hotel New York", h: "NoMad (20 W 29th St)", b: "Manhattan", pr: "FREE", c: "Workspace", d: "Every Day", hr: "All day", desc: "Massive communal tables, outlets everywhere, free WiFi, no purchase required. Best free coworking in Midtown.", s: "ace-hotel-lobby-workspace", sc: 9, tr: 8, lat: 40.7458, lng: -73.9882 },
  { n: "Capital One Café", p: "Capital One", h: "Union Sq / Herald Sq", b: "Manhattan", pr: "FREE / 50% off", c: "Workspace", d: "Every Day", hr: "All day", desc: "50% off drinks with CapOne card, free WiFi for everyone, coworking tables. Multiple NYC locations.", s: "capital-one-cafe-workspace", sc: 8, tr: 7, lat: 40.7350, lng: -73.9906 },
  { n: "Stavros Niarchos Library (NYPL)", p: "New York Public Library", h: "Midtown (455 5th Ave)", b: "Manhattan", pr: "FREE", c: "Workspace", d: "Every Day", hr: "All day", desc: "Free public space, rooftop terrace with city views, incredible WiFi, silent study spaces. Open to all.", s: "stavros-niarchos-library-workspace", sc: 10, tr: 8, lat: 40.7525, lng: -73.9820 },
  { n: "Devoción Coffee", p: "Devoción", h: "Williamsburg / Flatiron", b: "Brooklyn", pr: "~$5", c: "Workspace", d: "Every Day", hr: "All day", desc: "Fast WiFi, plant-filled industrial space, exceptional specialty coffee. Arrive early for outlets.", s: "devocion-workspace", sc: 8, tr: 9, lat: 40.7161, lng: -73.9646 },

  // ─── FREE EVENTS ───
  { n: "Chelsea Gallery Openings", p: "Chelsea Gallery District", h: "Chelsea (W 20s–W 30s)", b: "Manhattan", pr: "FREE", c: "Free Events", d: "Thursday", hr: "6–8pm", desc: "Free wine, beer, and snacks while viewing world-class contemporary art at 200+ galleries. Every Thursday.", s: "chelsea-gallery-openings", sc: 9, tr: 8, lat: 40.7496, lng: -74.0040 },
  { n: "Tech Meetups via Luma", p: "Various NYC venues", h: "Citywide", b: "Citywide", pr: "FREE", c: "Free Events", d: "Varies", hr: "Evenings", desc: "Free pizza, drinks, and networking with founders and VC scouts. Check Luma app for this week's events.", s: "tech-meetups-luma", sc: 8, tr: 9, lat: 40.7580, lng: -73.9855 },
  { n: "Whitney Museum Free Fridays", p: "Whitney Museum of American Art", h: "Meatpacking District (99 Gansevoort)", b: "Manhattan", pr: "FREE", c: "Free Events", d: "Friday", hr: "5–10pm", desc: "Free museum admission, rooftop drinks, live music, and stunning Hudson River views every Friday evening.", s: "whitney-museum-free-friday", sc: 9, tr: 8, lat: 40.7396, lng: -74.0089 },
  { n: "Bryant Park Events", p: "Bryant Park Corporation", h: "Midtown (6th Ave & 42nd)", b: "Manhattan", pr: "FREE", c: "Free Events", d: "Varies", hr: "All day", desc: "Rotating free events: movie nights, fitness classes, ice skating in winter, carousel, free concerts.", s: "bryant-park-free-events", sc: 8, tr: 8, lat: 40.7536, lng: -73.9832 },
  { n: "Smorgasburg Williamsburg", p: "Smorgasburg", h: "East River State Park (Kent Ave)", b: "Brooklyn", pr: "Varies (~$10–$15)", c: "Free Events", d: "Saturday (seasonal)", hr: "11am–6pm", desc: "NYC's legendary outdoor food market with 100+ vendors every Saturday spring through fall. Free entry.", s: "smorgasburg-williamsburg", sc: 9, tr: 9, lat: 40.7177, lng: -73.9649 },
  { n: "Brooklyn Museum First Saturdays", p: "Brooklyn Museum", h: "Crown Heights (200 Eastern Pkwy)", b: "Brooklyn", pr: "FREE", c: "Free Events", d: "Saturday (first of month)", hr: "5–11pm", desc: "Monthly free evening with live music, dancing, art-making, film, and special exhibitions. NYC's best free party.", s: "brooklyn-museum-first-saturdays", sc: 10, tr: 9, lat: 40.6712, lng: -73.9636 },
  { n: "MoMA Uniqlo Nights", p: "MoMA (11 W 53rd St)", h: "Midtown (11 W 53rd St)", b: "Manhattan", pr: "FREE for NY residents", c: "Free Events", d: "Friday", hr: "5:30–8:30pm", desc: "Free admission to MoMA every Friday evening for NY State residents. Wine bar, last-minute tour talks, world-class art.", s: "moma-uniqlo-nights", sc: 9, tr: 8, lat: 40.7614, lng: -73.9776 },

  // ─── LATE NIGHT ───
  { n: "Wo Hop 24hr Cantonese", p: "Wo Hop", h: "Chinatown (17 Mott St)", b: "Manhattan", pr: "$8–$15", c: "Late Night", d: "Every Day", hr: "24 hours", desc: "NYC's most famous all-night Chinese restaurant since 1938. Wonton soup, roast duck, and clay pots at 4am. Zero judgment.", s: "wo-hop-chinatown-late-night", sc: 9, tr: 8, lat: 40.7145, lng: -73.9995 },
  { n: "Corner Bistro Burger (Until 3:30am)", p: "Corner Bistro", h: "West Village (331 W 4th St)", b: "Manhattan", pr: "$9–$12", c: "Late Night", d: "Every Day", hr: "Until 3:30am", desc: "Cash-only dive bar serving legendary $9 Bistro Burgers until 3:30am nightly. Cheap beers and perfect greasy burgers.", s: "corner-bistro-late-night", sc: 9, tr: 9, lat: 40.7350, lng: -74.0050 },
  { n: "Artichoke Pizza Until 5am", p: "Artichoke Basille's Pizza", h: "East Village (321 E 14th St)", b: "Manhattan", pr: "$5–$7/slice", c: "Late Night", d: "Friday, Saturday", hr: "Until 5am weekends", desc: "Iconic thick-cut artichoke and crab slices served until 5am on weekends. NYC institution for 15+ years.", s: "artichoke-pizza-late-night", sc: 9, tr: 9, lat: 40.7313, lng: -73.9811 },
  { n: "Kunjip 24hr Korean BBQ", p: "Kunjip", h: "K-Town (9 W 32nd St)", b: "Manhattan", pr: "$15–$25/pp", c: "Late Night", d: "Every Day", hr: "24 hours", desc: "24-hour Korean BBQ at the heart of Koreatown. Tabletop grills, banchan, dolsot bibimbap, soju. Never closes.", s: "kunjip-24hr-korean-bbq", sc: 9, tr: 8, lat: 40.7484, lng: -73.9880 },
  { n: "Kellogg's Diner 24hr", p: "Kellogg's Diner", h: "Williamsburg (518 Metropolitan Ave)", b: "Brooklyn", pr: "$10–$18", c: "Late Night", d: "Every Day", hr: "24 hours", desc: "Classic 1940s stainless diner open 24 hours. Massive plates, strong coffee, pancakes at 3am, perfect disco fries.", s: "kelloggs-diner-24hr", sc: 8, tr: 8, lat: 40.7138, lng: -73.9512 },
  { n: "Sarge's Deli 24hr", p: "Sarge's Deli & Diner", h: "Murray Hill (548 3rd Ave)", b: "Manhattan", pr: "$10–$20", c: "Late Night", d: "Every Day", hr: "24 hours", desc: "NYC Jewish deli open 24/7 since 1964. Pastrami sandwiches stacked sky-high, matzoh ball soup, cheesecake.", s: "sarges-deli-24hr", sc: 8, tr: 7, lat: 40.7430, lng: -73.9765 },
  { n: "Empanada Mama Late Night", p: "Empanada Mama", h: "Hell's Kitchen (765 9th Ave)", b: "Manhattan", pr: "$3–$5/empanada", c: "Late Night", d: "Every Day", hr: "Until 4am", desc: "Latin empanadas stuffed with 30+ fillings until 4am. Spinach, chicken, beef, shrimp — massive and cheap.", s: "empanada-mama-late-night", sc: 9, tr: 8, lat: 40.7613, lng: -73.9906 },
  { n: "Katz's Deli Weekend Late Night", p: "Katz's Delicatessen", h: "Lower East Side (205 E Houston)", b: "Manhattan", pr: "$18–$25", c: "Late Night", d: "Friday, Saturday", hr: "Until 2:45am", desc: "The world-famous pastrami sandwich at Katz's stays open until 2:45am on weekends. Since 1888. Worth every penny.", s: "katzs-deli-late-night", sc: 9, tr: 9, lat: 40.7224, lng: -73.9873 },

  // ─── DIM SUM ───
  { n: "Nom Wah Tea Parlor", p: "Nom Wah Tea Parlor", h: "Chinatown (13 Doyers St)", b: "Manhattan", pr: "$4–$8/dish", c: "Dim Sum", d: "Every Day", hr: "10:30am–9pm", desc: "NYC's oldest dim sum parlor, open since 1920 on the crooked Doyers St. Order-from-menu style, no carts. Must-do.", s: "nom-wah-tea-parlor", sc: 10, tr: 9, lat: 40.7150, lng: -73.9986 },
  { n: "Jing Fong Classic Cart Dim Sum", p: "Jing Fong", h: "Chinatown (20 Elizabeth St)", b: "Manhattan", pr: "$3–$6/dish", c: "Dim Sum", d: "Every Day", hr: "9:30am–3pm", desc: "Traditional Hong Kong-style cart service in a massive ballroom. Har gow, siu mai, egg tarts pushed to your table.", s: "jing-fong-dim-sum", sc: 8, tr: 7, lat: 40.7163, lng: -73.9981 },
  { n: "88 Palace Underground Dim Sum", p: "88 Palace", h: "Chinatown (88 E Broadway)", b: "Manhattan", pr: "$4–$7/dish", c: "Dim Sum", d: "Every Day", hr: "8am–4pm", desc: "Hidden underground food court beneath a mall on E Broadway. Multiple vendors, off-tourist-track prices, insiders-only.", s: "88-palace-underground-dim-sum", sc: 9, tr: 7, lat: 40.7132, lng: -73.9937 },
  { n: "Dim Sum Go Go Modern", p: "Dim Sum Go Go", h: "Chinatown (5 East Broadway)", b: "Manhattan", pr: "$5–$10/dish", c: "Dim Sum", d: "Every Day", hr: "10am–10pm", desc: "Modern dim sum with colorful dumpling skins, no cart service, all-day menu. Instagrammable and delicious.", s: "dim-sum-go-go-modern", sc: 8, tr: 8, lat: 40.7144, lng: -73.9967 },
  { n: "Nan Xiang Soup Dumplings (Flushing)", p: "Nan Xiang Xiao Long Bao", h: "Flushing (38-12 Prince St)", b: "Queens", pr: "$7–$10/basket", c: "Dim Sum", d: "Every Day", hr: "11am–9:30pm", desc: "Best XLB outside Shanghai. Soup dumplings, pan-fried pork buns, and scallion pancakes in the heart of Flushing.", s: "nan-xiang-flushing-dim-sum", sc: 10, tr: 9, lat: 40.7573, lng: -73.8313 },
  { n: "Golden Unicorn Banquet Dim Sum", p: "Golden Unicorn", h: "Chinatown (18 East Broadway)", b: "Manhattan", pr: "$4–$7/dish", c: "Dim Sum", d: "Every Day", hr: "9:30am–4pm (dim sum)", desc: "Classic Hong Kong banquet-hall dim sum on East Broadway. Full carts, massive space, great price-to-quality ratio.", s: "golden-unicorn-dim-sum", sc: 8, tr: 7, lat: 40.7138, lng: -73.9953 },

  // ─── DOLLAR EATS (new additions) ───
  { n: "Jin Mei Dumpling Bar", p: "Jin Mei", h: "Flushing (40-52 Main St)", b: "Queens", pr: "$5 for 15", c: "Dollar Eats", d: "Every Day", hr: "All day", desc: "15 handmade pork and chive dumplings for $5. Best dumpling value in the outer boroughs — cheaper than Chinatown.", s: "jin-mei-dumpling-bar-flushing", sc: 10, tr: 8, lat: 40.7598, lng: -73.8316 },
  { n: "A&A Bake & Doubles", p: "A&A Bake & Doubles", h: "Flatbush (481 Nostrand Ave)", b: "Brooklyn", pr: "$2–$3", c: "Dollar Eats", d: "Every Day", hr: "7am–3pm (sell out fast)", desc: "Trinidadian doubles: curried chickpea sandwiched in fried bara dough. NYC's best $2 breakfast. Arrives early or miss out.", s: "aa-bake-doubles-flatbush", sc: 10, tr: 9, lat: 40.6615, lng: -73.9504 },
  { n: "NY Dosas Washington Sq Cart", p: "Thiru Kumar's Cart", h: "Washington Square Park", b: "Manhattan", pr: "$4–$7", c: "Dollar Eats", d: "Monday–Saturday", hr: "12–5pm (weather permitting)", desc: "Legendary $4–$7 South Indian dosas from the world's most famous street cart. Cash only, usually a line.", s: "ny-dosas-washington-sq-cart", sc: 10, tr: 9, lat: 40.7308, lng: -73.9973 },
  { n: "Eight Jane Jian Bing (Flushing)", p: "Eight Jane", h: "Flushing (Queens)", b: "Queens", pr: "$5", c: "Dollar Eats", d: "Every Day", hr: "9am–4pm", desc: "Chinese street crepe loaded with egg, scallion, crispy wonton, hoisin, and chili sauce. $5 breakfast in Flushing.", s: "eight-jane-jian-bing-flushing", sc: 9, tr: 7, lat: 40.7590, lng: -73.8300 },
  { n: "Arepa Lady Jackson Heights", p: "Arepa Lady (María Piedad Cano)", h: "Jackson Heights (79th St & Roosevelt Ave)", b: "Queens", pr: "$3–$5", c: "Dollar Eats", d: "Thursday–Sunday", hr: "7pm–Midnight", desc: "Famous street cart arepas from the legendary Arepa Lady. White corn, cheese, chicharrón, mote. Cash only.", s: "arepa-lady-jackson-heights", sc: 10, tr: 9, lat: 40.7471, lng: -73.8838 },

  // ─── CHEAP EATS (new additions) ───
  { n: "Pio Pio Half Rotisserie Chicken", p: "Pio Pio", h: "Multiple NYC locations", b: "Manhattan", pr: "~$10", c: "Cheap Eats", d: "Every Day", hr: "11am–11pm", desc: "Half Peruvian rotisserie chicken with green sauce and sides for around $10. Multiple locations, consistent quality.", s: "pio-pio-half-chicken", sc: 9, tr: 8, lat: 40.7590, lng: -73.9883 },
  { n: "Sao Mai Pho (Under $10)", p: "Sao Mai", h: "Chinatown (203 Centre St)", b: "Manhattan", pr: "$9–$11", c: "Cheap Eats", d: "Every Day", hr: "10am–10pm", desc: "Giant bowls of Vietnamese pho under $10 in Manhattan. Also bun bo hue, banh mi, and rice plates at fair prices.", s: "sao-mai-pho-chinatown", sc: 9, tr: 8, lat: 40.7180, lng: -73.9997 },
  { n: "Russ & Daughters Bagel Counter", p: "Russ & Daughters Café", h: "Lower East Side (179 E Houston)", b: "Manhattan", pr: "$8–$14", c: "Cheap Eats", d: "Every Day", hr: "8am–4pm (café)", desc: "Counter service bagel with nova, cream cheese, and fixings from NYC's legendary appetizing shop since 1914.", s: "russ-daughters-bagel-counter", sc: 9, tr: 8, lat: 40.7225, lng: -73.9837 },
  { n: "Too Good To Go App Deals", p: "Too Good To Go (app)", h: "Citywide", b: "Citywide", pr: "$3–$6 (saves ~$15+)", c: "Cheap Eats", d: "Every Day", hr: "End of day", desc: "App-based mystery bags of surplus food from NYC restaurants and bakeries at 60-80% off. Find $4 bags worth $15.", s: "too-good-to-go-app", sc: 10, tr: 9 },
  { n: "Charles Pan-Fried Chicken (Harlem)", p: "Charles' Country Pan Fried Chicken", h: "Harlem (340 W 145th St)", b: "Manhattan", pr: "$10–$15", c: "Cheap Eats", d: "Thursday–Sunday", hr: "12pm–7pm (or sold out)", desc: "Legendary Harlem fried chicken: extra-crispy, hand-seasoned, pan-fried in cast iron. Sells out daily. Cash preferred.", s: "charles-pan-fried-chicken-harlem", sc: 10, tr: 9, lat: 40.8224, lng: -73.9399 },

  // ─── HAPPY HOUR (new additions) ───
  { n: "A10 Kitchen $9 Wings Happy Hour", p: "A10 Kitchen", h: "Boerum Hill (285 Atlantic Ave)", b: "Brooklyn", pr: "$9/order", c: "Happy Hour Food", d: "Tuesday–Sunday", hr: "4–7pm", desc: "Crispy double-fried wings for $9 during happy hour. Also discounted cocktails. Casual Brooklyn neighborhood spot.", s: "a10-kitchen-wings-hh-brooklyn", sc: 8, tr: 7, lat: 40.6883, lng: -73.9870 },
  { n: "The Laurels 6 Wings for $10", p: "The Laurels", h: "Park Slope (170 7th Ave)", b: "Brooklyn", pr: "$10 for 6 wings", c: "Happy Hour Food", d: "Monday–Friday", hr: "2–7pm", desc: "6 crispy chicken wings for $10 plus $5 cocktails and $4 drafts. Long happy hour window in Park Slope.", s: "the-laurels-wings-hh-brooklyn", sc: 8, tr: 7, lat: 40.6657, lng: -73.9795 },
  { n: "Maison Premiere $1 Oysters", p: "Maison Premiere", h: "Williamsburg (298 Bedford Ave)", b: "Brooklyn", pr: "$1/oyster", c: "$1 Oyster Deals", d: "Monday–Friday", hr: "4–6pm (or Mon all day)", desc: "$1 oysters at one of NYC's most celebrated oyster bars. Absinthe cocktails, beautiful garden. Get there early.", s: "maison-premiere-1-dollar-oysters", sc: 10, tr: 9, lat: 40.7146, lng: -73.9577 },

  // ─── BRONX ───
  { n: "Arthur Ave Italian Market", p: "Arthur Avenue Retail Market", h: "Belmont, The Bronx (2344 Arthur Ave)", b: "Bronx", pr: "$3–$12", c: "Street Food & Markets", d: "Monday–Saturday", hr: "6am–6pm", desc: "NYC's real Little Italy. Fresh mozzarella, porchetta sandwiches, pasta, cannoli, and pastries at unbeatable prices.", s: "arthur-ave-italian-market-bronx", sc: 9, tr: 8, lat: 40.8572, lng: -73.8823 },
  { n: "Com Tam Ninh Kieu (Bronx)", p: "Cơm Tấm Ninh Kiều", h: "Fordham, The Bronx (2415 Jerome Ave)", b: "Bronx", pr: "$8–$12", c: "Cheap Eats", d: "Every Day", hr: "9am–9pm", desc: "Vietnamese broken rice plates in the Bronx: grilled pork chop, egg, pickled veg, all for under $12. Hidden gem.", s: "com-tam-ninh-kieu-bronx", sc: 9, tr: 7, lat: 40.8631, lng: -73.8978 },

  // ─── STATEN ISLAND ───
  { n: "Denino's Tavern Square Pizza", p: "Denino's Pizzeria & Tavern", h: "Port Richmond, Staten Island (524 Port Richmond Ave)", b: "Staten Island", pr: "$14–$22/pie", c: "Pizza Slice Value", d: "Monday–Saturday", hr: "11:30am–11pm", desc: "Staten Island institution since 1937. Legendary thin-crust square pies in a classic tavern setting. Worth the ferry.", s: "deninos-staten-island-pizza", sc: 10, tr: 8, lat: 40.6280, lng: -74.1308 },

  // ─── BRONX (new additions) ───
  { n: "Feeding Tree Jamaican", p: "Feeding Tree", h: "South Bronx (892 Gerard Ave)", b: "Bronx", pr: "$10–$14", c: "Cheap Eats", d: "Monday–Saturday", hr: "11am–10pm", desc: "Hidden gem in the South Bronx serving great jerk chicken, oxtail, and rice & peas. Generous portions at unbeatable prices.", s: "feeding-tree-jamaican-bronx", sc: 9, tr: 7, lat: 40.8285, lng: -73.9207 },
  { n: "Zero Otto Nove Neapolitan Pizza", p: "Zero Otto Nove", h: "Belmont, Bronx (2357 Arthur Ave)", b: "Bronx", pr: "~$4/slice", c: "Pizza Slice Value", d: "Wednesday–Monday", hr: "12pm–10pm", desc: "Proper Neapolitan pizza on Arthur Ave, wood-fired and perfected. One of the best slices in the entire city.", s: "zero-otto-nove-pizza-bronx", sc: 9, tr: 8, lat: 40.8572, lng: -73.8823 },
  { n: "Madonia Brothers Bakery", p: "Madonia Brothers Bakery", h: "Belmont, Bronx (2348 Arthur Ave)", b: "Bronx", pr: "$2–$4", c: "Dollar Eats", d: "Monday–Saturday", hr: "7am–6pm", desc: "Third-generation Italian bakery on Arthur Ave. Cannoli, struffoli, bread, and pastries all under $5. A Bronx treasure since 1918.", s: "madonia-brothers-bakery-bronx", sc: 9, tr: 7, lat: 40.8571, lng: -73.8822 },
  { n: "La Morada Oaxacan", p: "La Morada", h: "Mott Haven, Bronx (308 Willis Ave)", b: "Bronx", pr: "$10–$14", c: "Cheap Eats", d: "Tuesday–Sunday", hr: "11am–9pm", desc: "Oaxacan restaurant in Mott Haven: tlayudas, mole negro, mezcal. Celebrated as the best Mexican food in the Bronx.", s: "la-morada-oaxacan-bronx", sc: 10, tr: 8, lat: 40.8081, lng: -73.9240 },
  { n: "Sabrosura Dominican Comfort Food", p: "Sabrosura", h: "Grand Concourse, Bronx (700 Grand Concourse)", b: "Bronx", pr: "$8–$12", c: "Cheap Eats", d: "Every Day", hr: "9am–10pm", desc: "Dominican comfort food on the Grand Concourse. Pollo guisado, mangu, pernil — massive portions at prices that can't be beat.", s: "sabrosura-dominican-bronx", sc: 8, tr: 6, lat: 40.8246, lng: -73.9267 },
  { n: "Full Moon Café Breakfast Platters", p: "Full Moon Café", h: "Pelham Bay, Bronx (600 Pelham Pkwy N)", b: "Bronx", pr: "$8–$14", c: "Cheap Eats", d: "Every Day", hr: "7am–10pm", desc: "Classic diner near Pelham Bay Park with massive breakfast platters and solid comfort food. Great everyday value.", s: "full-moon-cafe-bronx", sc: 7, tr: 5, lat: 40.8560, lng: -73.8524 },

  // ─── QUEENS (new additions) ───
  { n: "Jackson Diner Indian Lunch Buffet", p: "Jackson Diner", h: "Jackson Heights, Queens (37-47 74th St)", b: "Queens", pr: "$17 buffet", c: "Cheap Eats", d: "Every Day", hr: "11:30am–10pm", desc: "Legendary Indian lunch buffet in Jackson Heights with 20+ dishes: naan, biryani, curries. One of NYC's greatest dining deals.", s: "jackson-diner-buffet-jackson-heights", sc: 10, tr: 9, lat: 40.7468, lng: -73.8909 },
  { n: "Himalayan Yak Momos", p: "Himalayan Yak", h: "Jackson Heights, Queens (72-20 Roosevelt Ave)", b: "Queens", pr: "$12–$16", c: "Cheap Eats", d: "Every Day", hr: "12pm–10pm", desc: "Tibetan-Nepali momos, thukpa noodle soup, and butter tea in Jackson Heights. Authentic and generous portions.", s: "himalayan-yak-jackson-heights", sc: 9, tr: 8, lat: 40.7474, lng: -73.8899 },
  { n: "Zabb Elee Isan Thai", p: "Zabb Elee", h: "Jackson Heights, Queens (71-28 Roosevelt Ave)", b: "Queens", pr: "$12–$16", c: "Cheap Eats", d: "Every Day", hr: "11am–10pm", desc: "James Beard-nominated Isan Thai with serious heat: duck laab, papaya salad, and boat noodles that will blow your mind.", s: "zabb-elee-isan-thai-jackson-heights", sc: 9, tr: 9, lat: 40.7479, lng: -73.8908 },
  { n: "Leo's Latticini Mozzarella Hero", p: "Leo's Latticini (Mama's)", h: "Corona, Queens (46-02 104th St)", b: "Queens", pr: "$10–$13", c: "Cheap Eats", d: "Monday–Saturday", hr: "8am–6pm", desc: "Cash-only deli serving the legendary mozzarella hero: house-made fresh mozz, roasted peppers, and prosciutto on Italian bread.", s: "leos-latticini-mamas-corona-queens", sc: 10, tr: 9, lat: 40.7516, lng: -73.8637 },
  { n: "Tortilleria Nixtamal Tacos", p: "Tortilleria Nixtamal", h: "Corona, Queens (104-05 47th Ave)", b: "Queens", pr: "$3–$4/taco", c: "Dollar Eats", d: "Thursday–Sunday", hr: "9am–6pm", desc: "Handmade masa tortillas using the real nixtamal process — the best tortillas in NYC, bar none. Tacos $3–4.", s: "tortilleria-nixtamal-corona-queens", sc: 10, tr: 8, lat: 40.7450, lng: -73.8627 },
  { n: "Lhasa Fast Food Tibetan Momos", p: "Lhasa Fast Food", h: "Jackson Heights, Queens (37-50 75th St)", b: "Queens", pr: "$5–$8", c: "Dollar Eats", d: "Every Day", hr: "10am–9pm", desc: "Tiny authentic Tibetan street food spot: momo dumplings and thenthuk noodle soup at incredibly cheap prices.", s: "lhasa-fast-food-jackson-heights", sc: 9, tr: 7, lat: 40.7462, lng: -73.8901 },
  { n: "Don Peppe Italian Red Sauce", p: "Don Peppe", h: "South Ozone Park, Queens (135-58 Lefferts Blvd)", b: "Queens", pr: "~$20 family-style", c: "Cheap Eats", d: "Wednesday–Sunday", hr: "12pm–10pm", desc: "No-menu, cash-only Italian red sauce institution serving family-style platters. Unbeatable value for a full meal.", s: "don-peppe-south-ozone-park-queens", sc: 9, tr: 7, lat: 40.6797, lng: -73.8212 },
  { n: "Pho Bang Vietnamese Pho", p: "Pho Bang", h: "Elmhurst, Queens (82-90 Broadway)", b: "Queens", pr: "$9–$13", c: "Cheap Eats", d: "Every Day", hr: "10am–10pm", desc: "Legendary Vietnamese pho in Elmhurst with massive bowls and rich broth for around $10. Cash preferred.", s: "pho-bang-elmhurst-queens", sc: 9, tr: 7, lat: 40.7349, lng: -73.8786 },

  // ─── BROOKLYN (new additions) ───
  { n: "Di Fara Pizza Legendary Slice", p: "Di Fara Pizza", h: "Midwood, Brooklyn (1424 Ave J)", b: "Brooklyn", pr: "$5–$6/slice", c: "Pizza Slice Value", d: "Wednesday–Sunday", hr: "12pm–8pm", desc: "Dom DeMarco's legendary slice: hand-cut fresh basil, perfect char, impeccable ingredients. Worth the trip and the line.", s: "di-fara-pizza-midwood-brooklyn", sc: 10, tr: 9, lat: 40.6243, lng: -73.9614 },
  { n: "Totonno's Coal-Fired Pizza", p: "Totonno's", h: "Coney Island, Brooklyn (1524 Neptune Ave)", b: "Brooklyn", pr: "$22–$26/pie", c: "Pizza Slice Value", d: "Thursday–Sunday", hr: "1pm–8pm", desc: "NYC's oldest operating pizzeria (1924). Coal-fired, thin-crust, cash only. A true pilgrimage for pizza lovers.", s: "totonno-coney-island-pizza-brooklyn", sc: 10, tr: 8, lat: 40.5759, lng: -73.9874 },
  { n: "Roberta's Pizza by the Slice", p: "Roberta's", h: "Bushwick, Brooklyn (261 Moore St)", b: "Brooklyn", pr: "~$5/slice", c: "Pizza Slice Value", d: "Every Day", hr: "11am–12am", desc: "Cult Bushwick pizza institution. The takeout counter serves slices cheaper than dining in — great crust and creative toppings.", s: "robertas-pizza-slice-bushwick", sc: 8, tr: 10, lat: 40.7052, lng: -73.9338 },
  { n: "Court Street Grocers Roman Sandwich", p: "Court Street Grocers", h: "Carroll Gardens, Brooklyn (485 Court St)", b: "Brooklyn", pr: "~$14", c: "Cheap Eats", d: "Every Day", hr: "9am–8pm", desc: "Acclaimed deli sandwiches in Carroll Gardens. The Roman — mortadella, coppa, provolone — is legendary in Brooklyn.", s: "court-street-grocers-carroll-gardens", sc: 8, tr: 9, lat: 40.6782, lng: -73.9966 },
  { n: "Lucali Pizza Pie", p: "Lucali", h: "Carroll Gardens, Brooklyn (575 Henry St)", b: "Brooklyn", pr: "~$28/pie", c: "Pizza Slice Value", d: "Wednesday–Monday", hr: "5pm–10pm", desc: "Cash BYOB Carroll Gardens gem with no slices — full pies only, but split one and it's among the best deals in Brooklyn.", s: "lucali-pizza-carroll-gardens-brooklyn", sc: 9, tr: 10, lat: 40.6800, lng: -74.0012 },
  { n: "Hometown Bar-B-Que Brisket", p: "Hometown Bar-B-Que", h: "Red Hook, Brooklyn (454 Van Brunt St)", b: "Brooklyn", pr: "$12–$18", c: "Cheap Eats", d: "Wednesday–Sunday", hr: "12pm–9pm", desc: "Texas-style BBQ in Red Hook. The brisket alone justifies the trip, and lunch portions keep it under $15.", s: "hometown-bbq-red-hook-brooklyn", sc: 9, tr: 8, lat: 40.6741, lng: -74.0127 },
  { n: "Tacos el Bronco Late Night", p: "Tacos el Bronco", h: "Sunset Park, Brooklyn (708 5th Ave)", b: "Brooklyn", pr: "$3–$4/taco", c: "Taco Tuesday", d: "Every Day", hr: "9am–midnight", desc: "Late-night taco truck legend in Sunset Park. Suadero, cabeza, al pastor — cash only and absolutely the real deal.", s: "tacos-el-bronco-sunset-park-brooklyn", sc: 10, tr: 9, lat: 40.6467, lng: -73.9944 },
  { n: "Glady's Caribbean Happy Hour", p: "Glady's", h: "Crown Heights, Brooklyn (788 Franklin Ave)", b: "Brooklyn", pr: "$6 cocktails", c: "Happy Hour Food", d: "Tuesday–Friday", hr: "5–7pm", desc: "Caribbean happy hour in Crown Heights: $6 cocktails and discounted apps. Rotating menu, great vibes, and a lovely space.", s: "gladys-caribbean-hh-crown-heights", sc: 8, tr: 8, lat: 40.6699, lng: -73.9571 },
  { n: "Colson Patisserie Belgian Pastries", p: "Colson Patisserie", h: "Park Slope, Brooklyn (374 9th St)", b: "Brooklyn", pr: "$3–$5", c: "Dollar Eats", d: "Every Day", hr: "8am–7pm", desc: "Belgian patisserie in Park Slope. Quiche, croissants, and butter cookies all under $6. A beloved Brooklyn neighborhood staple.", s: "colson-patisserie-park-slope-brooklyn", sc: 8, tr: 7, lat: 40.6682, lng: -73.9866 },

  // ─── MANHATTAN (new additions) ───
  { n: "Num Pang Cambodian Sandwich", p: "Num Pang", h: "Midtown (140 E 41st St)", b: "Manhattan", pr: "$10–$13", c: "Cheap Eats", d: "Monday–Friday", hr: "10:30am–8pm", desc: "Cambodian sandwich shop in Midtown. Tiger shrimp, pulled duroc pork, and catfish sandwiches — excellent fast-casual value.", s: "num-pang-midtown-manhattan", sc: 8, tr: 9, lat: 40.7511, lng: -73.9793 },
  { n: "Ivan Ramen Shio Ramen", p: "Ivan Ramen", h: "Lower East Side (25 Clinton St)", b: "Manhattan", pr: "$14–$18", c: "Cheap Eats", d: "Every Day", hr: "12pm–10pm", desc: "Ivan Orkin's celebrated ramen. The shio ramen is a masterpiece, with lunch-only specials available under $16.", s: "ivan-ramen-les-manhattan", sc: 9, tr: 9, lat: 40.7155, lng: -73.9834 },
  { n: "Superiority Burger Vegetarian", p: "Superiority Burger", h: "East Village (119 Ave A)", b: "Manhattan", pr: "$6–$12", c: "Hot Restaurant Value", d: "Every Day", hr: "11:30am–10pm", desc: "Brooks Headley's legendary vegetarian burgers and sundaes in the East Village. Lines form for a reason — everything under $14.", s: "superiority-burger-east-village", sc: 8, tr: 10, lat: 40.7262, lng: -73.9815 },
  { n: "Joe's Shanghai Soup Dumplings", p: "Joe's Shanghai", h: "Chinatown (9 Pell St)", b: "Manhattan", pr: "$12–$16", c: "Cheap Eats", d: "Every Day", hr: "11am–10:30pm", desc: "The original soup dumpling spot. Crab and pork XLB in bamboo steamers — still the best XLB in Chinatown.", s: "joes-shanghai-xlb-chinatown", sc: 9, tr: 8, lat: 40.7152, lng: -73.9978 },
  { n: "Nha Trang Centre Vietnamese Pho", p: "Nha Trang Centre", h: "Chinatown (148 Centre St)", b: "Manhattan", pr: "$9–$13", c: "Cheap Eats", d: "Every Day", hr: "10:30am–9:30pm", desc: "No-frills Vietnamese pho and banh mi in Chinatown. Giant bowls for under $13, fast service and great value.", s: "nha-trang-centre-chinatown", sc: 8, tr: 7, lat: 40.7162, lng: -74.0003 },
  { n: "Dominique Ansel DKA Pastry", p: "Dominique Ansel Bakery", h: "SoHo (189 Spring St)", b: "Manhattan", pr: "$5–$8", c: "Dollar Eats", d: "Every Day", hr: "8am–6pm", desc: "The cronut inventor's bakery. The DKA (Dominique's Kouign Amann) at $6 is a buttery, caramelized masterpiece worth every cent.", s: "dominique-ansel-dka-soho", sc: 8, tr: 9, lat: 40.7245, lng: -74.0028 },
  { n: "Eataly Pizza al Taglio Counter", p: "Eataly La Pizza", h: "Flatiron (200 5th Ave)", b: "Manhattan", pr: "~$5/slice", c: "Pizza Slice Value", d: "Every Day", hr: "11am–10pm", desc: "Roman-style pizza al taglio sold by weight at the Eataly counter. Fast, quality Italian ingredients — better than most NYC slices.", s: "eataly-pizza-al-taglio-flatiron", sc: 8, tr: 9, lat: 40.7421, lng: -73.9890 },
  { n: "Westville Lunch Market Plate", p: "Westville", h: "Chelsea (246 W 18th St)", b: "Manhattan", pr: "$13–$15", c: "Cheap Eats", d: "Monday–Friday", hr: "12pm–4pm", desc: "Lunch market plates: choose 3 sides plus a protein for $13–$15. Healthy, filling, and excellent value in Chelsea.", s: "westville-lunch-plate-chelsea", sc: 8, tr: 7, lat: 40.7440, lng: -74.0008 },
  { n: "Kish-Kash Israeli-Moroccan Couscous", p: "Kish-Kash", h: "West Village (149 W 14th St)", b: "Manhattan", pr: "$12–$15", c: "Cheap Eats", d: "Tuesday–Sunday", hr: "12pm–10pm", desc: "Israeli-Moroccan couscous and mezze in the West Village. Lunch under $15 including a glass of wine — a rare deal.", s: "kish-kash-west-village-manhattan", sc: 9, tr: 8, lat: 40.7396, lng: -74.0020 },
  { n: "Economy Candy Bulk Treats", p: "Economy Candy", h: "Lower East Side (108 Rivington St)", b: "Manhattan", pr: "$2–$6", c: "Dollar Eats", d: "Every Day", hr: "10am–6pm", desc: "Beloved LES candy shop since 1937. Nostalgic bulk candy, old-school chocolates, and halvah — cheap, fun, and historic.", s: "economy-candy-les-manhattan", sc: 7, tr: 8, lat: 40.7196, lng: -73.9882 },

  // ─── LATE NIGHT (new additions) ───
  { n: "Excellent Pork Chop House Taiwanese", p: "Excellent Pork Chop House", h: "Chinatown (3 Doyers St)", b: "Manhattan", pr: "$8–$12", c: "Late Night", d: "Every Day", hr: "10am–midnight", desc: "Cash-only Taiwanese landmark on Doyers St. Braised pork chop over rice and scallion pancakes — a Chinatown institution until midnight.", s: "excellent-pork-chop-house-chinatown", sc: 9, tr: 7, lat: 40.7148, lng: -73.9986 },
  { n: "Los Tacos No.1 Late Night Chelsea", p: "Los Tacos No.1", h: "Chelsea Market (75 9th Ave)", b: "Manhattan", pr: "$4–$5/taco", c: "Late Night", d: "Every Day", hr: "Until midnight", desc: "Late-night tacos at Chelsea Market. Adobada and carne asada done right — open until midnight for a real-deal fix.", s: "los-tacos-no1-chelsea-market-late", sc: 9, tr: 9, lat: 40.7424, lng: -74.0048 },
  { n: "Vanessa's Dumpling Late Night", p: "Vanessa's Dumpling House", h: "Lower East Side (118 Eldridge St)", b: "Manhattan", pr: "$1.50–$5", c: "Late Night", d: "Every Day", hr: "Until midnight", desc: "Pan-fried and steamed dumplings until midnight. The best dollar-for-dollar value on the Lower East Side at any hour.", s: "vanessas-dumpling-les-late-night", sc: 9, tr: 8, lat: 40.7181, lng: -73.9917 },
  { n: "Mamoun's Falafel Until 5am", p: "Mamoun's Falafel", h: "Greenwich Village (119 MacDougal St)", b: "Manhattan", pr: "$7–$9", c: "Late Night", d: "Every Day", hr: "Until 5am", desc: "Open until 5am — falafel and shawarma wraps from a Greenwich Village institution since 1969. NYC's best late-night wrap.", s: "mamouns-falafel-greenwich-village-late", sc: 8, tr: 9, lat: 40.7302, lng: -74.0003 },

  // ─── HAPPY HOUR (new additions) ───
  { n: "Attaboy Craft Cocktails Early", p: "Attaboy", h: "Lower East Side (134 Eldridge St)", b: "Manhattan", pr: "~$15", c: "Happy Hour Food", d: "Monday–Friday", hr: "6–8pm", desc: "No-menu craft cocktail bar on the LES. Walk in early evening before the line forms for bespoke cocktails from a legendary team.", s: "attaboy-craft-cocktails-les", sc: 7, tr: 9, lat: 40.7181, lng: -73.9922 },
  { n: "Clover Club Classic Cocktail HH", p: "Clover Club", h: "Cobble Hill, Brooklyn (210 Smith St)", b: "Brooklyn", pr: "$8 cocktails", c: "Happy Hour Food", d: "Monday–Friday", hr: "4–7pm", desc: "Classic cocktail bar happy hour in Cobble Hill: $8 cocktails, $5 beers, and bar snacks in a beautifully designed space.", s: "clover-club-hh-cobble-hill-brooklyn", sc: 8, tr: 8, lat: 40.6840, lng: -73.9942 },

  // ─── WORKSPACE (new additions) ───
  { n: "NYPL Rose Main Reading Room", p: "New York Public Library (Main Branch)", h: "Midtown (476 5th Ave)", b: "Manhattan", pr: "FREE", c: "Workspace", d: "Every Day", hr: "10am–6pm", desc: "Iconic Beaux-Arts reading rooms with free WiFi and no purchase needed. The Rose Main Reading Room is one of NYC's most stunning spaces.", s: "nypl-rose-reading-room-midtown", sc: 10, tr: 8, lat: 40.7533, lng: -73.9822 },
];
